### ISSUE TITLE
Using multiple PDFs in same page - canvas rendering error[BUG]

### ISSUE THREAD

**Issue by prafulrajhm** [ansu5555/pdf-viewer-reactjs#61]
I am using this package to display pdfs for different points. Let's say I have 20 points on a page. Clicking on any point will open the respective PDF. It works fine for the first 3-4 sets of points, but when the user keeps going on... at some point, it will throw canvas render error.

1. Have multiple points on a page (each point is a component)
2. Clicking on a point will open pdf viewer 
3. Keep clicking points and observe at some point, you will see error

**Expected behavior**
Canvas render error should be handled

![chrome_2021-02-15_12-38-53](https://user-images.githubusercontent.com/44769213/107916055-9bcd6a80-6f8b-11eb-82e0-6f44b75eac22.png)

**PDF File**
any file will do

**Details (please complete the following information):**
 - Device: Desktop
 - OS: Windows 8.1
 - Browser chrome
 - Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by ansu5555** [comment]
fixed in version 2.2.3

**Comment by redday059** [comment]
It is not fixed. I spent a lot of time adapting the code that worked in the version 2.0.0  and it has appeared that in this version other bugs (which are closed as well) happen more often.

**Comment by ansu5555** [comment]
> It is not fixed. I spent a lot of time adapting the code that worked in the version 2.0.0 and it has appeared that in this version other bugs (which are closed as well) happen more often.

It's fixed in 2.2.3 if you are able to produce create a bug and give the steps to reproduce
